### ISSUE TITLE
That old devil CAULD style guide

### ISSUE THREAD

**Issue by ragamouf** [au-research/ARDC-23-things#53]
Are we repeating the "do you have a question...post to slack...tweet" refrain after each of the 3 levels for each thing? I'm noticing (in thing2 for example) that the refrain appears only once at the end of the 'whole' thing.

**Comment by tom-h** [comment]
Now that PR #48 has been merged, you should basically exclude the "get help / interact" material from the content of the things.

This text is automagically added, and there are technical limitations on how often and where it'll end up. It's also dependant on the eventual template and layout of the webpage version of the things. I'd like it in a spot where it's always visible, for instance, rather than repeated multiple times through the page.

**Comment by ragamouf** [comment]
ah-hah - so you're telling me the refrain will be handled by the header you've designed, and I don't need to insert the refrain at all. Cooliio.

**Comment by tom-h** [comment]
Exactly :-)
